name: CI Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
    tags: [ '*' ]

  workflow_dispatch:

env:
  KONG_VERSION: 2.0.5

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout github branch
        uses: actions/checkout@v2

      - name: Build 
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: |
            git clone https://github.com/Kong/kong-pongo.git ../kong-pongo
            cd ../kong-pongo && git reset --hard 19ee5c20c1c68510430f637cae8bfa43836ab810 && cd "$OLDPWD"
            ../kong-pongo/pongo.sh clean && ../kong-pongo/pongo.sh up && ../kong-pongo/pongo.sh build && ../kong-pongo/pongo.sh run